.gitmodules
solvers/minion/build.rs
solvers/minion/src/main.rs

@ozgurakgun 
The `minion_main` function is now exposed in libminion (https://github.com/minion/minion/pull/10), meaning I no longer need the custom fork of it.
This PR updates the submodule to point to `minion/minion`.
It also suppresses the `vendor (not tracked)` messages that appears in `git status` when Minion has folders untracked by git (such as build files).

Minion: point submodule to upstream (minion/minion)

---

Cargo.lock
Cargo.toml
src/main.rs

We are trying to represent:
```
find a,b,c : int(1..3)
such that a + b + c = 4
```
Influenced by Conjure's internal representation, not sure about refs/boxes etc yet.
Creating PR to get feedback, will add simple testing before I am ready to merge.
Next steps:

an initial go at representing a model

---

.github/workflows/rustfmt.yml

This is a suggested alternative way to do the rust formatting check -- rather than using an action, just run `cargo fmt --check`. This will output a diff, and fail, if `cargo fmt` hasn't been run.
Disadvantages: Doesn't automatically edit your commit to do the formatting.
Advantages: Should work and not require nightly and other things :)

Use cargo fmt directly, instead of an action

---

.github/workflows/doc-coverage.yml
.github/workflows/minion-tests.yml

This PR adds a Github action to generate documentation coverage reports.
This is currently will just be for informational purposes, and is viewable in the CI job summary.
Would appreciate this to be squash merged when done.

Documentation Coverage CI

---

solvers/chuffed/build.rs
solvers/chuffed/build.sh
solvers/chuffed/clean.sh
solvers/chuffed/compile_flags.txt
solvers/chuffed/src/lib.rs
solvers/chuffed/src/main.rs
solvers/chuffed/wrapper.cpp
solvers/chuffed/wrapper.h

This pull request is mainly to commit my progress to the main branch. Everything compiles correctly but running main causing an address boundary error that needs to be solved.
I have based main.rs off vendor/examples/template.cpp as this was the simplest chuffed problem I could find. I have implemented the required rust wrappers in lib.rs to implement template.cpp in rust. I think that trying to re create a simple Chuffed problem before trying to implement the XYZ problem will make the process much simpler as I want to stick as close to chuffed as possible to minimize mistakes
My initial approach for figuring out what functions to implement in Rust was to look at the minizinc parser that Chuffed uses. The problem with this is that the entire parser is auto-generated and therefore …

Add wrappers for basic chuffed functions and example program using these wrappers

---

.github/workflows/chuffed.yml
.github/workflows/code-coverage-deploy.yml
.github/workflows/code-coverage.yml
.github/workflows/doc-coverage.yml
.github/workflows/essence-feature-stats.yml
.github/workflows/format.yml
.github/workflows/kissat.yml
.github/workflows/minion.yml
.github/workflows/oxide.yml
.github/workflows/update-caches.yml

Modifying github actions to only run for pushes to the main branch.
One visible effect of running it on all branches was that PRs made from branches in the repository were being triggered twice. For example depandabot.
Also add workflow_dispath to more actions, since I don't see why not...

Do not run github actions on all branches

---

solvers/chuffed/build.rs
solvers/chuffed/src/lib.rs
solvers/chuffed/tests/chuffed_basic_run.rs
solvers/chuffed/wrapper.cpp
solvers/chuffed/wrapper.h

As discussed in https://github.com/conjure-cp/conjure-oxide/pull/34, I have turned the example program main into a test called `chuffed_basic_run.rs`.
I have decided to keep the `main.rs` file for now as I believe it will be useful for further development. The test simply checks that running the ffi bindings/wrappers does not cause a crash. In order to show the test case has passed I have used an `assert!(true)` at the end of the test function as without any kind of assert the test doesn't seem to run. Is there a better way of doing this? Happy to get suggestions on this as well as the test as a whole

Turn example main program into rust test

---

.github/workflows/code-coverage-deploy.yml
.github/workflows/code-coverage.yml
.github/workflows/doc-coverage.yml
.github/workflows/oxide.yml
etc/scripts/gen_coverage_all.sh

Fixes the CI paths as discussed in #53.
This is based on-top of #53 so #53 should be merged first.

Workspace Refactor: CI paths

---

.github/dependabot.yml

and also check them once a month instead of once a week.

dependabot: group pip updates

---

solvers/chuffed/build.rs
solvers/minion/build.rs

We were using the .parse_callbacks(Box::new(bindgen::CargoCallbacks))
option of bindgen to invalidate the build based on included files.
We always re-run ./configure in build.sh - this was invalidating the
build because the configure script updates the last modified timestamps
of generated headerfiles, even if the file contents themselves have not
changed.
We already rebuild on C++ changes as both chuffed and minion have
rerun-if-changed=vendor, rerun-if-changed=wrapper.h added manually.
Therefore, the bindgen functionality that does this is not needed. We
can assume if vendor/ has changed, then the configure generated headers
have changed - we do not need to track these directly.

Hotfix: fix minion and chuffed always rebuilding

---

solvers/minion/src/lib.rs

I may have vastly underestimated the complexity of the issue, but the recent CI failures (addressed in #138) may have been occurring as a result of a missing import in `solvers/minion`.

Fix minion CI

---

Cargo.toml

Chuffed-rs does not compile on lab machines. 
Making it non default means that running `cargo test` / `cargo build` on the workspace will now succeed on the school lab machines.

Make chuffed-rs non-default member of workspace.

---

conjure_oxide/src/lib.rs
conjure_oxide/src/rewrite.rs
crates/conjure_core/src/ast.rs

As per the rust meeting today, this is the basic form of the tree walker and rewriting algorithm. Currently, this is just a depth-first search that tries to apply all the rules to each expression in the tree - Returning the new expression if it can be rewritten or recursing through the expression's sub-expressions if it cannot.
Very soon I will be optimizing this slightly by marking nodes as dirty or clean and only searching through dirty nodes which will save some work. 
Everything seems to build properly on fedora Linux but there are most likely some errors in here that I have not yet spotted. If you see any errors or spots for improvement please let me know!

Basic rewriting algorithm/tree walker

---

Cargo.toml
doc/README.md
doc/index.md
readme.md
tools/gen_docs.sh

This PR adds a few documentation generation tweaks:
* Add an index.html to the conjure-cp.github.io/conjure-oxide/docs URL giving a directory of all documentation available.
* Simplify doc generation script.
* Put a link to the docs in the README.
To look at this locally, do ./tools/gen_docs.sh, then open target/doc/index.html in your browser.

Docs Generation Tweaks: Simplify script, add index.html

---

.github/workflows/docs-generate.yml

My last PR had some changes to doc generation.
This needs nightly rust, so changed the CI to use nightly. Should hopefully work now :)

CI Fix: Doc generation needs rust nightly

---

conjure_oxide/src/rewrite.rs
conjure_oxide/tests/rewrite_tests.rs

Just a small PR that adds a test for the rewrite function using the xyz problem which has been made into a nested expression compared to previous tests. 
My only question, before I think this is ready to merge, is whether I should add an assert that checks whether the rewritten expression is in the "simplest form". My reason for not including one was that I believe the simplest expression will change over time as we add more rules so this will have to be updated constantly but honestly, I am not sure how true this is as I have not been working on the actual rules themselves. Could someone closer to the work on rules let me know if an assert should be added?

Add test that checks if the write function can simplify the xyz problem

---

Cargo.lock
Cargo.toml
crates/uniplate/Cargo.toml
crates/uniplate/src/lib.rs
crates/uniplate/src/uniplate.rs
tools/gen_docs.sh

I whipped up some of the Uniplate functions and an example last night to show Felix - this PR puts them in this project.
A broad roadmap for this is:
* Implement all Uniplate operations.
* Add Zippers based on Uniplates.
* Add Biplates.
* Add derive macros for Uniplate, Zippers, Biplates.
Related to #177.

Uniplate Proof of Concept

---

.github/workflows/code-coverage-deploy.yml
.github/workflows/code-coverage-main.yml
.github/workflows/code-coverage.yml

@ozgurakgun this should work reliably now (i.e. not just in my fork). In short, the API call i was making may but is not guaranteed to give the PR that calls the workflow 🙄. Now doing it the way to docs recommend, which is to write the PR number to a file and put it in the artifact that goes to the second workflow. 
Works on my fork but, as usual, no guarantees.

CI: fix PR number not always appearing in coverage-deploy

---

conjure_oxide/src/parse.rs
conjure_oxide/src/rules/base.rs
conjure_oxide/src/rules/cnf.rs
conjure_oxide/src/rules/constant.rs
conjure_oxide/src/rules/minion.rs
conjure_oxide/src/solvers/kissat.rs
conjure_oxide/src/solvers/minion.rs
conjure_oxide/tests/integration/basic/bool/03/bool-03.expected-parse.serialised.json
conjure_oxide/tests/integration/basic/bool/03/bool-03.expected-rewrite.serialised.json
conjure_oxide/tests/integration/xyz/input.expected-parse.serialised.json
conjure_oxide/tests/integration/xyz/input.expected-rewrite.serialised.json
conjure_oxide/tests/model_tests.rs
conjure_oxide/tests/rewrite_tests.rs
crates/conjure_core/src/ast.rs

This PR adds metadata to all the current enum variants and should close [Issue 182](https://github.com/conjure-cp/conjure-oxide/issues/182). I have added metadata to all match calls on `Expression`, cloned existing metadata when `Expression` objects are being manipulated, and created new metadata where new `Expression` objects are being made. 
This is currently building and all tests are passing. Please note that I ran cargo test with the `ACCEPT=true` environment variable which has changed the expected json for some of the integration tests. I have looked over this and it seems to have changed it sensibly but if others could take a look at those changes specifically that would be great!
Additionally, I believe there might be some places where I have created new metadata instead of …

Add metadata to all enum variants

---

Cargo.lock
Cargo.toml
crates/conjure_core/Cargo.toml
crates/conjure_core/src/ast.rs
crates/enum_compatability_macro/Cargo.toml
crates/enum_compatability_macro/src/lib.rs

AST nodes (and enum variants generally) can support things that arn't just solvers!
Closes #166

rename #[solver] to #[compatible]

---

crates/conjure_core/src/solver/adaptors/kissat.rs
crates/conjure_core/src/solver/adaptors/minion.rs
crates/conjure_core/src/solver/mod.rs

In Rust, a trait T is "object safe" if it can be stored and used as a type. Non object safe traits do not allow type erasure or the storing any implementer of the trait as a Box<dyn Foo>.
See: https://doc.rust-lang.org/reference/items/traits.html#object-safety
The point of the solver adaptor in the first place was to be solver independent and generic - therefore, object safety is necessary. In particular, @gskorokhod wanted to put this into the global context so that we can define what SolverAdaptor to use depending on CLI arguments.
The idea is that we should "be a Java interface". The associated types of the trait are not needed, and the encapsulation should be strengthened such that the adaptor implementation does not even need to announce what types it uses internally in the first …

solver: make SolverAdaptor object safe

---

.gitignore
Cargo.lock
conjure_oxide/src/main.rs
conjure_oxide/src/utils/conjure.rs
conjure_oxide/src/utils/testing.rs
conjure_oxide/tests/generated_tests.rs
conjure_oxide/tests/model_tests.rs
conjure_oxide/tests/rewrite_tests.rs
crates/conjure_core/Cargo.toml
crates/conjure_core/src/context.rs
crates/conjure_core/src/lib.rs
crates/conjure_core/src/model.rs
crates/conjure_core/src/parse/example_models.rs
crates/conjure_core/src/parse/parse_model.rs
crates/conjure_core/src/solver/adaptors/kissat.rs
crates/conjure_core/src/solver/adaptors/minion.rs
crates/conjure_core/src/solver/mod.rs
crates/conjure_core/src/solver/states.rs
crates/conjure_core/src/solver/stats.rs
crates/conjure_core/src/stats/mod.rs
crates/conjure_core/src/stats/solver_stats.rs

Based on #278.
Add global and solver specific stats objects and save these to {filename}-stats.json for each integration test.
This provides the necessary json and infrastructure for the performance monitoring work for @PedroGGBM.
Adding Minion node count using this will be in the next PR.
See commit log for details.

Add Solver Statistics

---

.gitignore
Cargo.lock
conjure_oxide/Cargo.toml
conjure_oxide/src/main.rs
conjure_oxide/src/utils/conjure.rs
conjure_oxide/src/utils/testing.rs
conjure_oxide/tests/generated_tests.rs
conjure_oxide/tests/model_tests.rs
conjure_oxide/tests/rewrite_tests.rs
crates/conjure_core/Cargo.toml
crates/conjure_core/src/context.rs
crates/conjure_core/src/lib.rs
crates/conjure_core/src/model.rs
crates/conjure_core/src/parse/example_models.rs
crates/conjure_core/src/parse/parse_model.rs
crates/conjure_core/src/solver/adaptors/kissat.rs
crates/conjure_core/src/solver/adaptors/minion.rs
crates/conjure_core/src/solver/mod.rs
crates/conjure_core/src/solver/states.rs
crates/conjure_core/src/solver/stats.rs
crates/conjure_core/src/stats/mod.rs
crates/conjure_core/src/stats/solver_stats.rs

Based on #279 
This PR adds two convenience flags to the CLI:
```
--print-info-schema                Prints the schema for the info JSON then exits
--info-json-path <INFO_JSON_PATH>  Saves execution info as JSON to the given file-path
```
The former in particular may be helpful for @PedroGGBM  / those doing stuff with the stats JSON.
(to run with cargo run, do cargo run -- --print-info-schema )

Save context to info.json, and print json schema

---

.github/workflows/code-coverage-main.yml
.github/workflows/code-coverage.yml
.github/workflows/test.yml
.gitmodules
Cargo.lock
crates/conjure_core/src/solver/adaptors/minion.rs
solvers/minion/Cargo.toml
solvers/minion/build.rs
solvers/minion/src/lib.rs
solvers/minion/src/wrappers.rs
solvers/minion/tests/test_watchedor_reifyimply_1.rs

This PR provides a safe way  to get stats out of Minion's "TableOut" object, and uses this to put node count in the SolverStats. This is useful for performance benchmarking.

Get Stats out of Minion

---

.gitignore
conjure_oxide/src/main.rs
conjure_oxide/tests/integration/basic/bool/03/bool-03.expected-parse.serialised.json
conjure_oxide/tests/integration/basic/bool/03/bool-03.expected-rewrite.serialised.json
conjure_oxide/tests/integration/basic/min/01/input.expected-parse.serialised.json
conjure_oxide/tests/integration/basic/min/01/input.expected-rewrite.serialised.json
conjure_oxide/tests/integration/basic/min/02/input.expected-parse.serialised.json
conjure_oxide/tests/integration/basic/min/02/input.expected-rewrite.serialised.json
conjure_oxide/tests/integration/basic/min/03/input.expected-parse.serialised.json
conjure_oxide/tests/integration/basic/min/03/input.expected-rewrite.serialised.json
conjure_oxide/tests/integration/basic/min/04/input.expected-parse.serialised.json
conjure_oxide/tests/integration/basic/min/04/input.expected-rewrite.serialised.json
conjure_oxide/tests/integration/basic/min/05/input.expected-parse.serialised.json
conjure_oxide/tests/integration/basic/min/05/input.expected-rewrite.serialised.json
conjure_oxide/tests/integration/xyz/input.expected-parse.serialised.json
conjure_oxide/tests/integration/xyz/input.expected-rewrite.serialised.json
conjure_oxide/tests/plot_rewriter_optimization_performance.py
conjure_oxide/tests/rewrite_tests.rs
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/metadata.rs
crates/conjure_core/src/rule_engine/rewrite.rs
crates/conjure_core/src/stats/mod.rs
crates/conjure_core/src/stats/rewriter_stats.rs

This PR adds the "clean/dirty" optimisation. The rewriter algorithm and this optimisation are explained in [this issue](https://github.com/conjure-cp/conjure-oxide/issues/149). Clean nodes are skipped as there is no work to be done with them and dirty nodes are rewritten normally. Whenever a node is turned dirty then it's parent will make itself dirty. 
I have written a new test in `rewriter_tests` called `rewrite_solve_xyz_parameterized` which runs the rewriter over increasing "complex" XYZ models. Complex in this instance refers to the number of branches of execution so each version of the test will have an extra XYZ problem in the OR clause. Currently, this test runs from 1 to 4 number of XYZ problems mainly because 5 and above is quite slow - 5 XYZ problems in the OR runs for around …

Rewriter Optimization

---

Cargo.lock
conjure_oxide/src/main.rs
conjure_oxide/tests/generated_tests.rs
conjure_oxide/tests/rewrite_tests.rs
crates/conjure_core/Cargo.toml
crates/conjure_core/src/context.rs
crates/conjure_core/src/parse/example_models.rs
crates/conjure_core/src/rule_engine/resolve_rules.rs
crates/conjure_core/src/solver/mod.rs

This PR makes most things in main log to a file (instead of stdin), and adds a basic CLI to choose the target solver, enable extra rule sets, and choose whether to solve solutions to a file or print them to stdin
```
Usage: conjure_oxide [OPTIONS] [INPUT_ESSENCE]
Arguments:
[INPUT_ESSENCE]  The input Essence file [default: ./conjure_oxide/tests/integration/xyz/input.essence]
Options:
--extra-rule-sets <EXTRA_RULE_SETS>
Names of extra rule sets to enable
-s, --solver <SOLVER>
Solver family use (Minion by default)
--print-info-schema
Print the schema for the info JSON and exit
--info-json-path <INFO_JSON_PATH>
Save execution info as JSON to the given file-path.
-o, --output <OUTPUT>
Save solutions to a JSON file (prints to stdin by default)
-h, --help
Print help
-V, --version
Print version …
```

(minor) Add CLI

---

.github/workflows/code-coverage-main.yml
.github/workflows/code-coverage.yml
.github/workflows/test.yml
readme.md

In recent versions of the nightly / beta compilers, the use of linkme causes linker errors. (https://github.com/dtolnay/linkme/issues/94) This is due to the new linker set as default in these versions.
Add linker flags to nightly builds to revert to the old linker behaviour.
See:
- https://github.com/dtolnay/linkme/pull/88
- https://blog.rust-lang.org/2024/05/17/enabling-rust-lld-on-linux.html

Fix nightly build 

---

Cargo.lock
conjure_oxide/Cargo.toml
conjure_oxide/tests/rewrite_tests.rs
crates/conjure_core/Cargo.toml
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/ast/mod.rs
crates/conjure_core/src/ast/uniplate.rs
crates/conjure_core/src/rule_engine/rewrite.rs
crates/conjure_core/src/rules/base.rs
crates/conjure_core/src/rules/bubble.rs
crates/conjure_core/src/rules/minion.rs

~~Based on #308~~
* Use a manual implementation of Uniplate on Expression instead of the
derive macro.
* Use the new uniplate::biplate::Uniplate type instead of uniplate::uniplate::Uniplate. This will be the only Uniplate type in the future.
* Make conjure_core and conjure_oxide use a specific version of Uniplate (the latest commit on main at time of writing), instead of the latest "path" version of Uniplate.
These changes are to help development of the new Uniplate derive macro. 
In particular, pinning conjure_oxide to a specific version of uniplate will allow me to make breaking changes in Uniplate without having to keep fixing conjure_oxide -- instead, refactoring conjure_oxide to the new Uniplate can be done later in one go once Uniplate is more done.
In …

[Biplate Macro #1] conjure_core: use new Uniplate types for AST traversal

---

readme.md

The current link no longer works due to the contributors page in the wiki being split into multiple.

README: change link to contributors guide

---

conjure_oxide/build.rs
conjure_oxide/src/utils/conjure.rs
conjure_oxide/tests/gen_test_template
conjure_oxide/tests/generated_tests.rs
conjure_oxide/tests/integration/eprime-minion/README
conjure_oxide/tests/integration/eprime-minion/xyz/README
conjure_oxide/tests/integration/eprime-minion/xyz/input.eprime
conjure_oxide/tests/integration/eprime-minion/xyz/input.expected-minion.solutions.json
conjure_oxide/tests/integration/eprime-minion/xyz/input.expected-parse.serialised.json
conjure_oxide/tests/integration/eprime-minion/xyz/input.expected-rewrite.serialised.json

Add support for Essence Prime files (.eprime) to the test runner. This
change will help test Conjure Oxide as a replacement for Savile Row (the
current Essence Prime toolchain).
As Essence Prime is a subset of Essence, no extra work will be needed in
Conjure Oxide to support Essence Prime.

tests: add .eprime file extension support to the test runner

---

.github/workflows/code-coverage-deploy.yml

@ozgurakgun fixes syntax errors in Code coverage deploy runs.
For example, see https://github.com/conjure-cp/conjure-oxide/actions/runs/11131849553

ci: fix code coverage deploy syntax error

---

.github/workflows/code-coverage-deploy.yml
.github/workflows/code-coverage.yml

Update actions/download-artifact steps in code-coverage-deploy to v4. This requires uploaded artifacts to use actions/upload-artifact v4; therefore, this has also been updated. This fixes CI failures for code-coverage-deploy.
Github deprecated actions/download-artifact@v2 [1], making it cause automatic failures on workflows that use it. This causes our code coverage deploy jobs to fail [2].
1: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
2: https://github.com/conjure-cp/conjure-oxide/actions/runs/11134871648/job/30943894187

ci: update actions/download-artifact steps to v4

---

tools/test-summary.sh

Add a script to summarise whether Conjure Oxide integration tests pass, fail, or are disabled.
The primary use-case of this script over cargo test is that it reports on disabled tests (which cargo test does not know about). Also, the output of this script is presented in a more concise format for readability and future scripting.

add script to summarise test results, including disabled tests

---

.github/workflows/code-coverage-deploy.yml

The code-coverage-deploy workflow was failing, as it was trying to use historical lcov when it did not exist. This patch makes this step conditional on whether historical lcov exists or not.
https://github.com/conjure-cp/conjure-oxide/actions/runs/11146109623/job/30977305993

ci(code-coverage-deploy): only load historical lcov if it exists

---

.github/workflows/code-coverage-deploy.yml

- Checkout repository at the start of the comment job of code-coverage-deploy.yml.
This job relies on files in the repo; however, no copy of the repo was present, causing missing file errors.
- Fix syntax errors.
- Add conditionals to only add historical lcov info to the coverage comment if it exists. This information does not exist for the initial push to a PR or if Github's retention period for Actions data has passed.

fix(ci): checkout repository before generating code coverage comment

---

crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/ast/variables.rs
crates/conjure_core/src/model.rs
crates/conjure_core/src/rule_engine/rewrite.rs
crates/conjure_core/src/rule_engine/rule.rs
crates/conjure_core/src/rule_engine/rule_set.rs
crates/conjure_core/src/stats/rewriter_stats.rs

Improving documentation. Ideally, I would like to see all methods and methods` parametres in rule_engine documented.
TODO for rewrite.rs:

Improve docs

---

.gitignore
Cargo.lock
conjure_oxide/Cargo.toml
conjure_oxide/tests/generated_tests.rs
conjure_oxide/tests/integration/eprime-minion/partial-eval-add/config.toml
conjure_oxide/tests/integration/eprime-minion/partial-eval-add/input.eprime.disabled
crates/conjure_core/src/ast/expressions.rs
tools/test-summary.sh

Add a  configuration file, config.toml, to test cases, allowing
optional extra assertions to be enabled. These assertions are run on the
rewritten model.
Add the "vector_operators_have_partially_evaluated" assertion, allowing
testing of partial evaluation.
- **tools/test-summary: fix typo**
- **gitignore: add savile row solution files**
- **tester: when verbose is enabled, do not run tests in parallel**
When verbose printing is enabled in the tester, run tests in sequence
not parallel. When run in parallel, log messages from tests would appear
out of order and interspersed with logs from other test cases.
- **tester: allow enabling of extra assertions in config.toml**
Add an optional configuration file, config.toml, to test cases, allowing
optional extra assertions to be enabled. These …

tester: add config.toml and extra assertions

---

.github/workflows/code-coverage-deploy.yml

Quote shell arguments in code-coverage-deploy, hopefully fixing failing job [1].
1: https://github.com/conjure-cp/conjure-oxide/actions/runs/11303682269/job/31441100721

fix(ci): quote shell arguments in code-coverage-deploy

---

tools/test-summary.sh
tools/watch-tests.sh

Add a script watch-tests.sh to rerun the integration tests on changes to
the code or essence/eprime files. This gives a summary of failing tests
that is updated only when the source-code is.
While similar to bacon, bacon ignores ACCEPT=true, while this script
recognises it. Also, the output of this script is more readable, as it
uses the output of test-summary.sh not cargo test.

[eprime-arithmetic #1] tools: add watch-tests.sh to rerun integration tests on changes.

---

Cargo.lock
conjure_oxide/Cargo.toml
conjure_oxide/tests/generated_tests.rs

Add `pretty_assertions` crate to the integration tester for more readable output.
For example:

[eprime-arithmetic #2] tester: add pretty_assertions

---

conjure_oxide/src/main.rs

Remove default essence file parameter, requiring the model to solve to
be passed as an argument.
Closes: #396

cli: remove default Essence file

---

conjure_oxide/src/defaults.rs
conjure_oxide/src/lib.rs
conjure_oxide/src/main.rs
conjure_oxide/tests/generated_tests.rs

The CLI and tester are using different, hard-coded lists of rule-sets.
This causes models that run in the tester to fail when run with the CLI.
Replace these hard-coded values with a call to get_default_rule_sets(),
making the rule-sets used consistent.

fix(cli): make cli and tester use same rule-sets

---

.gitignore
Cargo.lock
conjure_oxide/Cargo.toml
conjure_oxide/src/main.rs

- Replace `structured_logger` with `tracing-subscribers` for log output.
- Add stderr logging, configurable with the --verbose flag, and the
RUST_LOG environment variable. The former changes the default log
level to DEBUG and makes print format more verbose, the latter adjusts
the log level.
Previously, we were using `log` to produce logs, and `structured_logger`
to put them in a file.
For debugging, I want configurable logging to stderr; however,
`structured_logger` does not allow different outputs to have different
formats (i.e. not JSON) or log levels.
We begin to use the `tracing` library as well as `log` for the rule
engine in PR #393 due to its better multi-threading support.
`trace_subscriber::fmt`, the `tracing` log writer used in this patch,
automatically intercepts `log` …

logging: use tracing for log output, and output to stderr

---

conjure_oxide/Cargo.toml
conjure_oxide/src/main.rs
crates/conjure_core/Cargo.toml
crates/conjure_core/src/rules/mod.rs

Add extra_check! macro, and the extra-rule-checks feature, allowing
rules to specify potentially expensive extra checks to be optionally
ran.
In the future, we will assume that the highest priority applicable rule
will be applied, regardless of where in the tree it applies. However, we
currently only apply the most applicable rule for our current
expression, ignoring any higher priority rules that could apply to child
expressions.
For example, consider partial evaluation. In general, we want to ensure
that the entire tree is in a simplest form before proceeding.
```
R1 (priority 10): collapse constants in addition
R2 (priority 5): f(M) ~> g(M) /\ h(M) /\ i(M) /\ ...
where M is a sum
```
For some expression `f(1+b+2)` we would want to apply R1 to the
arguments before doing R2; however, the …

rules: add extra_check! macro for conditionally compiling rule checks.

---

conjure_oxide/tests/generated_tests.rs
conjure_oxide/tests/integration/basic/bool/01/bool-01.expected-parse.serialised.json
conjure_oxide/tests/integration/basic/bool/01/bool-01.expected-rewrite.serialised.json
conjure_oxide/tests/integration/basic/bool/02/bool-02.expected-parse.serialised.json
conjure_oxide/tests/integration/basic/bool/02/bool-02.expected-rewrite.serialised.json
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/model.rs
crates/conjure_core/src/rule_engine/rule.rs
crates/conjure_core/src/rules/base.rs
crates/conjure_core/src/rules/partial_eval.rs

This PR is based on the Chris's and Oz's comment on Teams:
"
Chris:
I'd get existing PRs merged in first, but then it might be worth making a pass over empty constraints, I think (please check essence semantics  , and I'm not sure which are implemented yet):
and([]) = true
or([]) = false
sum([]) = 0
product([]) = 1
it's worth getting these right because (from experience), while no-one is likely to write these, they often end up getting created as parts of more interesting expressions.
Oz:
min([]) and max([]) are a bit different, as min([])=x is always false, but this falseness will arise naturally from the fact they will end up turning into an 'and([])' and an 'or([])', and the or will be false, so there is no need to special-case empty min([]) and max([]) (hopefully!)
we can define an …

Define behaviour for empty expressions

---

crates/conjure_core/src/rules/base.rs
crates/conjure_core/src/rules/minion.rs

Based on #420 
---
Move not(eq(...)) ~> neq and not(neq(...)) ~> eq rules into base ruleset, and raise their priorities to that of a simplification.
Both of these simplifications are Essence, solver-independent ones, not Minion specific.
As discussed with Oz, despite `not(eq)` being similar to `neq`, `neq` is a useful expression to use at "Essence level" due to undefinedness semantics.

rules: move negated eq/neq rules from Minion ruleset to Base

---

.github/workflows/checks.yml

Block any PRs with any commits called fixup!, amend!, squash! from being merged.
As discussed in #425, force pushing to existing commits is annoying to code reviewers. Another approach is to do `git commit --fixup <commit>` when you need to respond to a code review comment on a particular commit, then run `git rebase --autosquash` before merging to get rid of these fixup commits. (https://rietta.com/blog/git-rebase-autosquash-code-reviews/)
This way, code reviewers can see the code review changes to the PR in a linear order, but still keep a proper git history.

ci: block merging PRs with fixup! commits

---

CONTRIBUTING.md

Add guidance to not force push to PRs, as discussed in #430 and #425.
This new guidance roughly follows how LLVM does stuff:
https://llvm.org/docs//GitHub.html#updating-pull-requests

CONTRIBUTING.md: add do not force push advice

---

.github/workflows/code-coverage-deploy.yml
.github/workflows/code-coverage-main.yml
.github/workflows/code-coverage.yml
.github/workflows/docs.yml
.github/workflows/essence-feature-stats.yml
.github/workflows/format.yml
.github/workflows/test.yml

We don't expect our tests to take longer than 5 minutes at the moment. If they take a very long time this might be an error (like an infinite loop). We can increase the 5 minutes if we genuinely needed more time in the future.

Add a 5 minute time limit to CI actions

---

crates/randicheck/Cargo.toml
crates/randicheck/src/main.rs
crates/randicheck/src/tst.hs

Didn't use Oz's code, so doing a seperate PR as Leia seemed to get use out of reading #408 and it'd be nice to keep that seperate. Created using tree sitter queries primarily, and currently supports ADT's with Booleans, and functions using case statements. 
converts:
```
data X = L Bool | R Bool Bool
f :: X -> Bool 
f x = case x of
L True -> True
R False _ -> True
otherwise -> False  
```
to 
`
Haskell { adt: [DataType { Name: "X", Constructors: [Constructor { Types: [Custom("L"), Bool] }, Constructor { Types: [Custom("R"), Bool, Bool] }] }], fun: [Function { Name: "f", Inputs: [Custom("X")], Output: Bool, Body: [Case("x", Pattern { True_On: [Custom("L"), Custom("True")], gives: True }), Case("x", Pattern { True_On: [Custom("R"), Custom("False"), Custom("_")], gives: True }), Case("x", …

first prototype of randicheck 

---

.github/workflows/code-coverage-main.yml
.github/workflows/code-coverage.yml
tools/coverage.sh

Exclude rule macro invocations from the code coverage.
Fixes: #469

ci: exclude rule macros from coverage

---

crates/conjure_core/src/solver/adaptors/minion.rs

read_expr wasn't handling Expression::Atomic which caused conjure-oxide to fail on simple one variable constraint models such as 
```
language ESSENCE' 1.0 
find b: bool 
such that
b
```
Now we handle it.

Handle atomic in read_expr

---

.github/workflows/warnings.yml
conjure_oxide/tests/generated_tests.rs
crates/conjure_core/src/ast/variables.rs
crates/conjure_core/src/model.rs
crates/conjure_core/src/parse/parse_model.rs
crates/conjure_core/src/rule_engine/rewrite.rs
crates/conjure_core/src/rule_engine/rule.rs
crates/conjure_core/src/rules/constant.rs
crates/conjure_core/src/rules/minion.rs
crates/conjure_core/src/rules/partial_eval.rs
crates/conjure_core/src/rules/utils.rs
crates/conjure_macros/Cargo.toml
crates/enum_compatability_macro/Cargo.toml

the long list of warnings was getting annoying for me, so dealt with them all (I think!)
please take a look and see if any of this doesn't make sense stylistically.
also: should we have a separate ci run which makes warnings errors? would be too harsh to fail the main build, but if it was a separate ci run (non-matrix, just one run) that fails if there are any warnings that could be beneficial.
@conjure-cp/vip-students

deal with warnings

---

conjure_oxide/tests/generated_tests.rs

Tests were getting poisoned in case if the previous one paniced. This PR is fixing the bug.

Run later tests even if one panics

---

conjure_oxide/tests/integration/eprime-minion/bool/literals-to-wlit-1/input-expected-rule-trace.json
conjure_oxide/tests/integration/eprime-minion/bool/literals-to-wlit-1/input-generated-rule-trace.json
conjure_oxide/tests/integration/eprime-minion/bool/literals-to-wlit-1/input.expected-rewrite.serialised.json
conjure_oxide/tests/integration/eprime-minion/partial-eval-02-or-and/input-expected-rule-trace.json
conjure_oxide/tests/integration/eprime-minion/partial-eval-02-or-and/input-generated-rule-trace.json
conjure_oxide/tests/integration/eprime-minion/partial-eval-02-or-and/input.expected-rewrite.serialised.json
conjure_oxide/tests/integration/eprime-minion/partial-eval-or-and/input-expected-rule-trace.json
conjure_oxide/tests/integration/eprime-minion/partial-eval-or-and/input-generated-rule-trace.json
conjure_oxide/tests/integration/eprime-minion/partial-eval-or-and/input.expected-rewrite.serialised.json
crates/conjure_core/src/rules/minion.rs

Rename bool_to_wlit to not_literal_to_wliteral and make it only applicable for Not(Lit::Bool) expressions.
PR #473 made non negated boolean literals be converted to w-lit in the solver interface directly, making this rule mostly redundant.
As Not(Lit::Bool) is a nested expression, I still think it is reasonable to convert this to a watched literal in a rule instead of in the solver interface. Also, if it were to happen in the solver interface, there is a chance that the literal could be reified instead, which is not what we want.
Fixes: #474

refactor(rules/minion): only use bool_to_wlit for Not(Lit::Bool)

---

crates/conjure_core/src/ast/expressions.rs

Implement method of Expression to check whether an expression is an associative-commutative operator. The concept of an AC operator will be useful down the line for A-CSE, generic normalisation rules, and quantified expressions.
Related-issues: [#491,#493]
Fixes: #494

feat(ast): add Expression::is_associative_commutative_operator()

---

conjure_oxide/Cargo.toml
crates/conjure_core/Cargo.toml
crates/tree_morph/Cargo.toml

Didn't realise that `Biplate::with_children_bi` didn't exist, so another little uniplate update is needed.

update uniplate to v0.1.4

---

.gitignore
conjure_oxide/src/utils/conjure.rs
conjure_oxide/src/utils/testing.rs
conjure_oxide/tests/generated_tests.rs

Remove duplicate solutions found by Minion before comparing them against Conjures solutions.
Duplicates are introduced when we remove auxiliary variables from our solutions. Conjure. For example, `{__0=1,x=1,y=2}` and `{__0=0,x=1,y=2}` become identical to each other. As Conjure only has this solution once, the check would fail. This was causing problems in #425.
To fix this, this patch changes the type of solutions from `HashMap` to `BTreeMap`. This implements `Eq` and `Hash`, allowing us to use `.unique()` on our list of solutions.
Note that this patch only changes this in the tester; future work should make all solution fetching code use `BTreeMap`. Once this is done, the solution checking logic could likely be simplified as it was written the way it was because `HashMaps` could not be …

fix(tester): remove duplicate solutions when checking against Conjure

---

conjure_oxide/tests/generated_tests.rs
conjure_oxide/tests/integration/basic/min/01/config.toml
conjure_oxide/tests/integration/basic/neg/01-negeq/config.toml
conjure_oxide/tests/integration/basic/neg/02-nested-neg/config.toml
conjure_oxide/tests/integration/basic/neg/03-negated-expression/config.toml
conjure_oxide/tests/integration/basic/neg/04-negated-expression-nested/config.toml
conjure_oxide/tests/integration/basic/neg/05-sum/config.toml
conjure_oxide/tests/integration/basic/neg/06-sum-nested/config.toml
conjure_oxide/tests/integration/savilerow/divide-mod-novar/config.toml
conjure_oxide/tests/integration/savilerow/divide-mod/config.toml

* Cleanup the handling of missing / default values in test `config.toml` files.
Previously, flags were represented as `Option<bool>`. They had three possible values: true, false, or not specified. Now, these are represented as `bool`, with any missing values filled in with their defaults by serde during de-serialisation.
* Rename `skip_native_parser` config option to `use_native_parser`.
Previously, all other options were opt-in, apart from this one. Make this opt-in for consistency.

refactor(tester)!: cleanup defaults handling for test config.toml

---

crates/conjure_core/src/ast/atom.rs
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/ast/literals.rs
crates/conjure_core/src/rules/constant_eval.rs
crates/conjure_core/src/rules/minion.rs

Add more `TryFrom` and `From` impls for Atom. These new impls allow atoms to be cast directly to integers and bools.
Remove the following functions, as they are now redundant:
* `conjure_core::rules::constant_eval::unwrap_atom`
* `conjure_core::ast::expressions::Expression::as_atom`

refactor(ast): add more `TryFrom` and `From` impls for `Atom`

---

conjure_oxide/tests/generated_tests.rs

**Based on ~~#560~~ #566**
Add `run_solver` config value to integration tests `config.toml` files.
The main motivation for this change is to allow language feature implementation to be split into multiple PR's and still be testable.

feat(tester): add `run_solver` config value

---

conjure_oxide/tests/integration/basic/neg/05-sum/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/neg/06-sum-nested/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/sum/01-deeply-nested/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/sum/02-sum-put-in-aux-var/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/weighted-sum/01-simple/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/weighted-sum/02-needs-normalising/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/eprime-minion/partial-eval-01-add/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/eprime-minion/partial-eval-01-add/input.expected-rewrite.serialised.json
conjure_oxide/tests/integration/eprime-minion/partial-eval-add/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/eprime-minion/partial-eval-add/input.expected-rewrite.serialised.json
conjure_oxide/tests/integration/eprime-minion/xyz/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/experiment/works/max2/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/xyz/input-expected-rule-trace-human.txt
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/rules/constant_eval.rs
crates/conjure_core/src/rules/minion.rs
crates/conjure_core/src/rules/partial_eval.rs

**Closes: #515**
SumEq was used as an intermediate representation when rewriting `sum(...) = e2` into flat sumgeq / sumleq constraints.
Instead, decompose `sum(...) = e2` into `sum(...) <= e2 /\ sum(...) >= e2` and let the normal Minion process for flattening these convert these to Minion.
---
* PR #570:
`main` ← `nik/pr/add-mul/minion-conversion`
* **PR #571 (THIS ONE)**:
`nik/pr/add-mul/minion-conversion` ← `nik/pr/add-mul/remove-sum-eq`

Remove SumEq expression

---

conjure_oxide/tests/generated_tests.rs
conjure_oxide/tests/rewrite_tests.rs

Make human rule trace use a blocking writer.
I hope that this will fix our issues with macos CI in #516.
The failure is that, in some tests, the generated rule trace has some
lines missing from the end of the file compared to the expected rule
trace. Because of this, I suspect that the generated file is being read
before it has fully been written to. If this is the issue, blocking on
write would fix this.

fix(tester): make human rule trace writer blocking

---

Cargo.lock
crates/tree_morph/Cargo.toml
crates/tree_morph/src/commands.rs
crates/tree_morph/src/helpers.rs
crates/tree_morph/src/reduce.rs
crates/tree_morph/tests/depend_meta.rs

WIP adding useful out-of-the-box selection strategies for `tree-morph`.
I encourage people to comment ideas that might be useful! See `helpers.rs` for a current TODO list.

Additional tree-morph selection strategies

---

conjure_oxide/tests/integration/basic/abs/01-simple/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/abs/02-neg/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/abs/03-nested/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/abs/04-bounds/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/div/04/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/div/05/div-05-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/div/06/div-06-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/mod/04/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/mod/05/mod-05-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/mod/06/mod-06-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/neg/02-nested-neg/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/neg/03-negated-expression/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/neg/04-negated-expression-nested/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/neg/05-sum/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/neg/06-sum-nested/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/product/01-simple/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/sum/02-sum-put-in-aux-var/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/weighted-sum/03-simple-eq/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/minion_constraints/div_undefzero-03-nested/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/minion_constraints/div_undefzero-04-nested-neq/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/minion_constraints/div_undefzero-05-nested-noteq/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/minion_constraints/modulo_undefzero-03-nested/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/minion_constraints/modulo_undefzero-04-nested-neq/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/minion_constraints/modulo_undefzero-05-nested-noteq/input-expected-rule-trace-human.txt
crates/conjure_core/src/rules/minion.rs

Any reason not to do this? @niklasdewally

Unify flatten_*op rules into flatten_generic

---

conjure_oxide/src/main.rs

**Related issue: #552**
Add the `--[no]-check-equally-applicable-rules` and `--no-run-solver` command
line flags to enable/disable the rewriter's multiple equally applicable rules
assertion, and disable running the solver (e.g. for benchmarking)
**cli: add --check-equally-applicable-rules flag**
Add --check-equally-applicable-rules and
--no-check-equally-applicable-rules flags to enable / disable the naive
rewriters multiple equally applicable rules assertion via the
command line.
As before, this assertion is disabled by default.
---
**cli: add --no-run-solver flag**
Add --no-run-solver flag to disable the running of the solver. This
prints the rewritten model as output.
The motivation for this flag is comparing execution time against Savile
Row. In the future we may benchmark more …

Add CLI flags: `--[no]-check-equally-applicable-rules`, `--no-run-solver`

---

crates/conjure_core/src/rule_engine/rewrite_naive.rs

Only run the "rule not applicable" trace when Conjure Oxide is built in debug mode. 
For the test file `optimisations/implies-tautologies-cse/input.eprime`, this reduces execution time from 5.42s to 1.281s, a 75% improvement.
As this is only printed at the trace debug level, it is unlikely to be needed in a release build anyways.
DETAILS
Measurements were taken using `hyperfine`, building the project in release mode. Conjure oxide was ran using the `--no-run-solver` flag to mimic default Savile Row behaviour.
Profiling (using `samply`) revealed that 75% of our execution time was spent in this `trace`, even if we never print it.
For comparison, `savilerow -O0` takes 0.136s +- 0.004. Note that part of this may be due to us having no implication simplification rules, meaning that we would …

perf: only log rule not applicable in debug mode

---

conjure_oxide/tests/generated_tests.rs

Reapply https://github.com/conjure-cp/conjure-oxide/commit/6fde9643e37cfe4b6ba8d332109a0076000fd4e6 (fix(tester): make human rule trace writer blocking, 2025-01-08)
PR https://github.com/conjure-cp/conjure-oxide/pull/569 accidentally reverted this change, causing ACCEPT=true failures
on my Mac and some CI failures.
This commit also adds the previous fix to the new JSON logging layer.

fix(tester): re-apply MacOS CI fix (commit 6fde964)

---

conjure_oxide/tests/generated_tests.rs
crates/conjure_core/src/rule_engine/rewrite_naive.rs

- **bug(rewriter): only panic when there are multiple _equally_ applicable rules**
Fix the naive rewriter's `prop_multiple_equally_applicable` check so
that it panics when there are multiple equally applicable rules (i.e.
they have the same priority) instead of panicing any time there are
multiple applicable rules of any priority.
- **tester: enable `prop_multiple_equally_applicable` rewriter check**
Enable the `prop_multiple_equally_applicable` rewriter assertion in the
integration tester. This check panics if a given expression has two
rules of the same priority applicable to it.
All tests pass with this enabled.
For performance reasons, I think it is best to keep this disabled by
default in the CLI.
Issue: #552

Enable `prop_multiple_equally_applicable` by default in integration tests

---

crates/conjure_core/src/rule_engine/mod.rs
crates/conjure_core/src/rule_engine/resolve_rules.rs
crates/conjure_core/src/rule_engine/rule_set.rs
crates/conjure_core/src/rules/base.rs
crates/conjure_core/src/rules/bubble.rs
crates/conjure_core/src/rules/cnf.rs
crates/conjure_core/src/rules/constant_eval.rs
crates/conjure_core/src/rules/minion.rs
crates/conjure_macros/src/lib.rs

As discussed with Oz, RuleSet order is only ever used as a tie breaker in very specific circumstances. It's unnecessary and confusing for the user, so I suggest we remove it.
See this link for the original reasoning for adding it:
https://github.com/conjure-cp/conjure-oxide/wiki/Expression-rewriting%2C-Rules-and-RuleSets#ruleset-ordering
(This doc will need to be updated to avoid confusion)

refactor: Remove RuleSet order

---

.github/workflows/code-coverage-deploy.yml
.github/workflows/code-coverage.yml

A previous renaming of actions made code-coverage-deploy no longer
trigger, breaking code coverage comments and report publishing.
Fixes: #607

fix(ci): trigger code-coverage-deploy again

---

Cargo.lock
conjure_oxide/Cargo.toml
conjure_oxide/src/utils/conjure.rs

@lixitrixi updated rand to 0.9.0 in #635, but the conjure_oxide crate was not updated as part of that.

update rand to 0.9.0

---

Cargo.lock
conjure_oxide/Cargo.toml
crates/conjure_core/Cargo.toml
crates/tree_morph/Cargo.toml

Update to uniplate to v0.2.1. This changes Zipper::focus_mut() to return &mut T
not &T.

update uniplate to v0.2.1

---

Cargo.lock
conjure_oxide/Cargo.toml
conjure_oxide/src/main.rs
crates/conjure_core/Cargo.toml
crates/conjure_core/src/bug.rs
crates/conjure_core/src/error.rs
crates/conjure_core/src/parse/parse_model.rs

A mixture of a few improvements to how we handle errors:
added macros for parsing errors to also display the file,function & line in which the error was thrown. May be of note to @spritezs and @niklasdewally 
changed version to output the current git hash rather than 'conjure oxide 0.0.1'
changed bug to do both of the above, this also solves issue #404 
folded parse declaration into model_from_json
note that changing version required making input file an option (otherwise doing --version would need something after due to input file being mandatory) and thus some clones I don't particularly like, if someone knows how to get rid of these clones that would be appreciated.

Improving error handling

---

conjure_oxide/examples/solver-hello-minion.rs
conjure_oxide/src/utils/essence_parser.rs
conjure_oxide/src/utils/testing.rs
conjure_oxide/tests/model_tests.rs
conjure_oxide/tests/rewrite_tests.rs
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/ast/mod.rs
crates/conjure_core/src/ast/model.rs
crates/conjure_core/src/ast/submodel.rs
crates/conjure_core/src/ast/symbol_table.rs
crates/conjure_core/src/lib.rs
crates/conjure_core/src/metadata.rs
crates/conjure_core/src/parse/parse_model.rs
crates/conjure_core/src/rule_engine/rewrite.rs
crates/conjure_core/src/rule_engine/rewrite_naive.rs
crates/conjure_core/src/rule_engine/rewriter_common.rs
crates/conjure_core/src/rule_engine/rule.rs
crates/conjure_core/src/rules/base.rs
crates/conjure_core/src/rules/minion.rs
crates/conjure_core/src/rules/utils.rs
crates/conjure_core/src/solver/adaptors/minion/parse_model.rs
crates/conjure_core/src/solver/adaptors/sat_common.rs

Add `Submodel`, and refactor `Model` to be a wrapper over `Submodel`.
This commit is part of on-going work to add lexical scope to Conjure
Oxide and is a follow up to 863643260 (feat!: add parent symbol tables
(#680), 2025-02-17).
DETAILS
A `Submodel` represents a particular scope and holds the symbol-table
and constraints tree for that scope.
This commit refactors `Model` to be a wrapper over `Submodel`, and
removes methods operating on constraints and the symbol table from
`Model`, placing them in `Submodel` instead. A `Model` can be borrowed as
a `Submodel` using `as_submodel()` and `as_submodel_mut()`.
The language semantics of a top level model and a sub-model are
identical, so treating it as `Submodel` in most cases is valid.
`Model` is a separate type than `Submodel` for the …

feat!: add `Submodel`

---

crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/ast/model.rs
crates/conjure_core/src/ast/submodel.rs
crates/conjure_core/src/ast/symbol_table.rs
crates/conjure_core/src/rule_engine/mod.rs
crates/conjure_core/src/rule_engine/rewrite.rs
crates/conjure_core/src/rule_engine/rewrite_naive.rs
crates/conjure_core/src/rule_engine/rewriter_common.rs
crates/conjure_core/src/rule_engine/rule.rs
crates/conjure_core/src/rule_engine/submodel_zipper.rs
crates/conjure_core/src/rules/constant_eval.rs
crates/conjure_core/src/rules/partial_eval.rs

Add `Scope` expression variant, allowing submodels to be defined a model.
Change the rewriter so that it rewrites expressions inside their
submodels, using that submodels symbol table. This allows rules to apply
to variables defined in a local scope.
This commit is part of on-going work to add lexical scope to Conjure
Oxide, following on from 542c89ee7 (feat!: add `Submodel`, 2025-02-16).

feat: add `Expr::Scope`

---

Cargo.lock
conjure_oxide/Cargo.toml
conjure_oxide/examples/solver-hello-minion.rs
conjure_oxide/src/defaults.rs
conjure_oxide/src/main.rs
conjure_oxide/src/utils/essence_parser.rs
conjure_oxide/tests/generated_tests.rs
conjure_oxide/tests/parser_tests/dominance_simple.essence
conjure_oxide/tests/parser_tests/dominance_twice.essence
conjure_oxide/tests/parser_tests/mod.rs
conjure_oxide/tests/parser_tests/no_dominance.essence
conjure_oxide/tests/rewrite_tests.rs
crates/conjure_core/src/ast/atom.rs
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/ast/model.rs
crates/conjure_core/src/ast/name.rs
crates/conjure_core/src/rule_engine/resolve_rules.rs
crates/conjure_core/src/rules/constant_eval.rs
crates/conjure_core/src/rules/partial_eval.rs
crates/conjure_core/src/solver/mod.rs
crates/tree-sitter-essence/grammar.js

This PR adds support for parsing dominance relations.
It also contains some minor QOL improvements:
- `resolve_rule_sets` functions now take `&str` literals, not the `String` type.
This should reduce annoying type casting
- `Atom` variants now have an extra method `Atom::new_uref("name")`
This is a shorthand for `Atom::Reference(Name::UserName("name".to_string()))`
- `Name` now has `From` implemented for `&str`, `String`, and `i32`
Closes #671 and #670

feat: Parser and AST support for `dominanceRelation`

---

crates/tree_morph/src/commands.rs
crates/tree_morph/src/engine.rs
crates/tree_morph/tests/enum_rules.rs
crates/tree_morph/tests/lambda_calc.rs

Refactored mut_meta from using fn to Box<dyn FnOnce(&mut M)>
This change was needed as we I needed to move reduction.symbols into a mut_meta closure when implementing the Rule trait of treemorph for the conjure-oxide rule. (I'll link a PR later when I open one)

refactor(tree_morph): mut_meta to use Box<dyn FnOnce(&mut M)>

---

Cargo.toml

In our Hygiene CI, we ignore the unwrap_used and expect_used warnings . This commit sets them to allowed locally, making `cargo clippy` give the same output as CI.

fix: ignore unwrap and expect with clippy, like we do in CI

---

Cargo.lock
Cargo.toml
conjure_oxide/tests/integration/basic/matrix/01-indexing/config.toml
conjure_oxide/tests/integration/basic/matrix/01-indexing/input.eprime
conjure_oxide/tests/integration/basic/matrix/01-indexing/input.expected-parse.serialised.json
conjure_oxide/tests/integration/basic/matrix/01-indexing/input.expected-rewrite.serialised.json
conjure_oxide/tests/integration/basic/matrix/02-2d-slicing/config.toml
conjure_oxide/tests/integration/basic/matrix/02-2d-slicing/input.eprime
conjure_oxide/tests/integration/basic/matrix/02-2d-slicing/input.expected-parse.serialised.json
conjure_oxide/tests/integration/basic/matrix/02-2d-slicing/input.expected-rewrite.serialised.json
conjure_oxide/tests/integration/basic/matrix/03-domain-letting/config.toml
conjure_oxide/tests/integration/basic/matrix/03-domain-letting/input.eprime
conjure_oxide/tests/integration/basic/matrix/03-domain-letting/input.expected-parse.serialised.json
conjure_oxide/tests/integration/basic/matrix/03-domain-letting/input.expected-rewrite.serialised.json
crates/conjure_core/src/ast/domains.rs
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/ast/literals.rs
crates/conjure_core/src/ast/variables.rs
crates/conjure_core/src/parse/parse_model.rs
crates/conjure_core/src/rules/constant_eval.rs
crates/conjure_core/src/rules/partial_eval.rs
crates/conjure_core/src/rules/utils.rs
crates/conjure_core/src/solver/adaptors/minion/parse_model.rs
solvers/kissat/Cargo.toml

- **feat(ast): add Matrix types**
Add matrix literals, domains, indexing, and slicing to the AST.
As in Savile Row, indexing and slicing can possibly be undefined -
adding safe variants of these is left to a future commit.
- **feat(parse): parse matrix domains, indexing, and slicing**
Parse matrix domains, domain lettings, indexing, and slicing.
Matrix literals will be parsed in a future PR.

add matrix ast types and parse domains,indexing, and slicing

---

conjure_oxide/tests/generated_tests.rs
conjure_oxide/tests/integration/basic/div/01/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/matrix/01-indexing/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/matrix/02-2d-slicing/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/matrix/03-domain-letting/input-expected-rule-trace-human.txt
crates/conjure_core/src/rule_engine/rewrite_naive.rs

Before this commit, the tester was not creating expected rule trace files on ACCEPT=true. This commit fixes this with the following changes:
+ Set validate_traces tester option to true by default to generate and check
rule trace files
+ On ACCEPT=true, update expected rule traces before it is checked against the generated rule traces.
+ Re-add model printing to the rule traces.

fix(tester): fix generation of rule trace files

---

.github/workflows/hygiene.yml
Makefile
tools/show-help-minified.make

Create a Makefile containing our PR hygiene checks, and the commands necessary to fix it. Refactor the hygiene CI to call this Makefile.
This allows the running of the hygiene tests used in CI locally using `make check`. Having CI call the Makefile  ensures that the local and CI versions will always be consistent.
The fix/fix-dirty commands wrap the correct cargo clippy and cargo fmt flags to auto-fix these issues.
This Makefile is self-documenting, and help can be viewed by running `make`.

ci: move hygiene checks to `Makefile`, allowing them to be ran locally

---

crates/conjure_core/src/rule_engine/rewrite_naive.rs
crates/conjure_core/src/stats/rewriter_stats.rs

Add missing stats (rewriter running time, number of rule applications, etc) to the naive rewriter.
These were reported by the old rewriter and used for performance testing, but the naive reporter does not currently report stats which breaks some of our performance testing code

fix: collect run stats for naive rewriter

---

conjure_oxide/tests/integration/basic/comprehension/02/config.toml
conjure_oxide/tests/integration/basic/comprehension/02/input.expected-minion.solutions.json
conjure_oxide/tests/integration/basic/matrix/08-index-is-expr/config.toml
conjure_oxide/tests/integration/basic/matrix/08-index-is-expr/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/matrix/08-index-is-expr/input.eprime
conjure_oxide/tests/integration/basic/matrix/08-index-is-expr/input.expected-minion.solutions.json
conjure_oxide/tests/integration/basic/matrix/08-index-is-expr/input.expected-parse.serialised.json
conjure_oxide/tests/integration/basic/matrix/08-index-is-expr/input.expected-rewrite.serialised.json
conjure_oxide/tests/integration/basic/matrix/09-index-is-expr-offset/config.toml
conjure_oxide/tests/integration/basic/matrix/09-index-is-expr-offset/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/basic/matrix/09-index-is-expr-offset/input.eprime
conjure_oxide/tests/integration/basic/matrix/09-index-is-expr-offset/input.expected-minion.solutions.json
conjure_oxide/tests/integration/basic/matrix/09-index-is-expr-offset/input.expected-parse.serialised.json
conjure_oxide/tests/integration/basic/matrix/09-index-is-expr-offset/input.expected-rewrite.serialised.json
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/rules/base.rs
crates/conjure_core/src/rules/constant_eval.rs
crates/conjure_core/src/rules/matrix/repr_matrix.rs
crates/conjure_core/src/rules/minion.rs
crates/conjure_core/src/rules/partial_eval.rs
crates/conjure_core/src/solver/adaptors/minion/parse_model.rs
solvers/minion/src/run.rs

- **feat(minion): rewrite __inDomain(variable,...) to `w-inintervalset`**
Rewrite the internal `__inDomain(variable,...)` constraint to the
`w-inintervalset` constraint, allowing it to be solved with Minion.
We currently only have the constant evaluation of this, which occurs
when `variable` is a literal. This commit adds solver support for when
variables (and thus any arbitrary expression via flattening) are
As __inDomain is generated while making matrix indexing and slicing
safe, the main use of this will be when matrices are sliced/indexed by
decision variables. As this is not supported at all yet, it was
difficult to construct a test case for this at time of writing. This
work will be tested once matrices can be indexed by variables and
arbitrary non-constant expressions.
Closes: #736 …

 Solve matrices indexed by non-constant expressions

---

conjure_oxide/src/cli.rs
conjure_oxide/src/main.rs
conjure_oxide/src/solve.rs
conjure_oxide/src/test_solve.rs
conjure_oxide/src/utils/testing.rs
conjure_oxide/tests/generated_tests.rs

* PR #742:
`main` ← `nik/validate-conjure-flag`
* **PR #743 (THIS ONE)**:
`nik/validate-conjure-flag` ← `nik/validate-conjure-flag-2`
---
Add test-solve subcommand. This subcommand runs a model through Conjure
Oxide and Conjure, and ensures that the solutions returned are the same.
This is similar to the ACCEPT=true mode of the integration tester, but
can be called ad-hoc on any input file, so is more useful for scripting.
This command mostly uses functionality already found in the solve
subcommand and the integration tester. This commit moves some stuff
found in these into functions, to ensure that this subcommand stays in
sync with changes in both.

feat(cli): add test-solve subcommand

---

conjure_oxide/src/cli.rs
conjure_oxide/src/help_text.txt
conjure_oxide/src/main.rs
conjure_oxide/src/print_info_schema.rs
conjure_oxide/src/solve.rs
conjure_oxide/src/test_solve.rs
conjure_oxide/src/utils/testing.rs
conjure_oxide/tests/generated_tests.rs

Tidy the CLI code, and add sub-commands.
As a consequence of this latter change, to run conjure oxide, one must
now do `cargo run -- solve <input>` or `conjure_oxide solve <input>`.
This is because I could not find a good way to do default arguments with
clap.
Other tidying includes:
* Move CLI flags into a separate file
* Move logging setup into its own function
* Move things for each subcommand into their own files.
The motivation of this work is to allow more subcommands to be added in
the future.
Before this change, we had the `--print-info-schema` flag that ignored
all other flags, just printed the schema, and exited. Using proper
subcommands is a more scalable way to add features like this, with the
added advantage that subcommands can have their own arguments.

cli!: tidy things into sub-commands

---

crates/conjure_core/src/rule_engine/rule.rs

This PR is created to fix #734

fix: update new_top only if reduction contains new_top

---

conjure_oxide/tests/integration/bugs/domain-lettings-in-comprehensions-leak-vars-into-scope/config.toml
conjure_oxide/tests/integration/bugs/domain-lettings-in-comprehensions-leak-vars-into-scope/input-expected-rule-trace-human.txt
conjure_oxide/tests/integration/bugs/domain-lettings-in-comprehensions-leak-vars-into-scope/input.eprime
conjure_oxide/tests/integration/bugs/domain-lettings-in-comprehensions-leak-vars-into-scope/input.expected-minion.solutions.json
conjure_oxide/tests/integration/bugs/domain-lettings-in-comprehensions-leak-vars-into-scope/input.expected-parse.serialised.json
conjure_oxide/tests/integration/bugs/domain-lettings-in-comprehensions-leak-vars-into-scope/input.expected-rewrite.serialised.json
conjure_oxide/tests/integration/savilerow/langford/langford-expected-rule-trace-human.txt
conjure_oxide/tests/integration/savilerow/langford/langford.expected-rewrite.serialised.json
crates/conjure_core/src/rules/subsitute_lettings.rs

This PR contains a bug fix for substituting domain lettings inside comprehensions, and other miscellaneous fixes to this rule.
See the changelog below for details:
---
- **test: bug/domain-lettings-in-comprehensions-leak-vars-into-scope**
Add test-case for the following bug:
```
letting DOM be domain int(1..3)
find a: matrix [DOM] of DOM
$ currently, when substituting DOM in the below comprehension, a and all its
$ representations are added to the comprehensions' symbol table!
such that
and([a[i] = i |i:DOM])
```
- **fix: only apply subsitute_domain_lettings to the local scope**
* Make substitute_domain lettings only substitute domains in variables in
the local scope, instead of all parent scopes.
This fixes the bug described in 730d5ab86 (test: …

fix: `substitute_domain_lettings` bug in nested scopes

---

Cargo.lock
Cargo.toml
conjure_oxide/Cargo.toml
conjure_oxide/src/lib.rs
conjure_oxide/tests/essence_macro_tests/mod.rs
conjure_oxide/tests/mod.rs
crates/conjure_core/src/ast/atom.rs
crates/conjure_essence_macros/Cargo.toml
crates/conjure_essence_macros/src/expand.rs
crates/conjure_essence_macros/src/expression.rs
crates/conjure_essence_macros/src/lib.rs
crates/conjure_essence_parser/src/errors.rs
crates/conjure_essence_parser/src/lib.rs
crates/conjure_essence_parser/src/parser/expression.rs
crates/conjure_essence_parser/src/parser/letting.rs
crates/conjure_essence_parser/src/parser/parse_exprs.rs
crates/conjure_essence_parser/src/parser/parse_model.rs
crates/tree-sitter-essence/grammar.js

> If {thing} is so good, why didn't they make {thing} 2?
> (c) unknown
This PR implements the alternative approach to parsing Essence at compile time, as discussed in the comments for #710.
It achieves the same results (complete with metavar support!) with significantly less complexity.
It also attempts to produce some semi-useful compile time errors for bad input. 
```rust
#[test]
fn test_metavar_const() {
let x = 4;
let expr = essence_expr!(&x + 2);
assert_eq!(
expr,
Expression::Sum(
Metadata::new(),
Box::new(matrix_expr![
Expression::Atomic(Metadata::new(), Atom::new_ilit(4)),
Expression::Atomic(Metadata::new(), Atom::new_ilit(2))
])
)
);
}
```

feat(essence macro): constructing essence AST from strings at compile time

---

conjure_oxide/src/utils/testing.rs

Normalising solutions didn't have a case for integer Literals, leading to errors on any test which included ints when using ACCEPT=true

fixing bug where accept=true testing would fail

---

conjure_oxide/build.rs
crates/tree-sitter-essence/bindings/rust/build.rs

Fix unnecessary rebuilding of the `conjure_oxide` and
`tree-sitter-essence` crates.
* Fix typo in `conjure_oxide/build.rs`. This was checking for a
change to a file that no longer exists (gen_test_template); as this
check always failed, a rebuild was always triggered.
* Rebuild `tree-sitter-essence` on change to the `grammar.js` file, not
`parser.c`. The `build.rs` file for `tree-sitter-essence` always
regenerated `parser.c`. As Rust's rebuild-on-changed mechanism is
timestamp based, this regeneration would always cause rebuilds of the
`tree-sitter-essence` crate.

fix(build): unnecessary rebuilding of conjure_oxide, tree-sitter-essence

---

crates/conjure_core/src/rule_engine/rule.rs

in #756 I missed the other definition of MorphRule. This PR adds the same change I've made there but for that other definitoin

fix: don't apply any transformation if reduction is empty

---

.github/workflows/nightly.yml

Do not run tests in the nightly CI workflow.
These test runs were failing due to Conjure not being installed;
however, the Linux build environment cannot run Conjure due to Conjure
requiring glibc 2.29, and the build environment using glibc 2.28.
(unfortunately a glibc 2.29 docker image is not available).
In the future, we will run tests nightly using the existing workflow,
and only trigger the nightly CI workflow if this passes. This how
Conjure does it. See #857.

fix(ci): do not run tests in nightly CI workflow

---

doc/crate_imports.gv

Adds a Graphviz dot diagram showing our crate structure to doc. By describing it using dot, we can easily edit the diagram when structure changes. It should be easy to edit it automatically via a script that parses relevant `Cargo.toml` files, but I am not doing that yet.

doc: Add a crate structure diagram

---

crates/conjure_core/src/ast/ac_operators.rs
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/ast/mod.rs

**Duplicate of #863, which was reverted due to a botched squash-merge**
---
Add `ACOperatorKind` type, an enum of all the associative-commuative operations in Conjure Oxide. Using this, this commit provides methods to get the operator kind for an expression, and to get the identity value and skipping operator for an operation.
The identity value and skipping operators will be helpful for improving comprehensions down the line.
Closes: #493

feat: add `AcOperatorKind`

---

Cargo.toml
conjure_oxide/src/utils/conjure.rs
conjure_oxide/src/utils/testing.rs
crates/conjure_core/src/ast/domains.rs
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/ast/literals.rs
crates/conjure_core/src/ast/matrix.rs
crates/conjure_core/src/ast/mod.rs
crates/conjure_core/src/ast/name.rs
crates/conjure_core/src/solver/adaptors/minion/adaptor.rs
crates/conjure_core/src/solver/adaptors/minion/parse_model.rs
crates/conjure_rules/src/matrix/repr_matrix.rs
crates/conjure_rules/src/records.rs
crates/conjure_rules/src/representation/matrix_to_atom.rs
crates/conjure_rules/src/representation/record_to_atom.rs
crates/conjure_rules/src/representation/tuple_to_atom.rs
crates/conjure_rules/src/tuple.rs

Reduce the size of `Name` and `AbstractLiteral` types by boxing large
fields. This causes a reduction in the sizes of `Literal`, `Atom` and
`Expression`.
+ `Name` was reduced from 56 bytes to 32 bytes
+ `AbstractLiteral` was reduced from 80 bytes to 32 bytes
+ `Literal` was reduced from 80 bytes to 32  bytes
+ `Atom` was reduced from 80 bytes to 40 bytes
+ `Expression` was reduced from 272 bytes to 152 bytes
As an enum has the size of its largest variants, having a few large
outlier variants in an enum wastes space. As we clone our AST types a
lot during rewriting, reducing their size also improves performance by
making memory copying of them faster.
The largest variants of the `Expression` type are those that contain 3
atom fields (FlatIneq, FlatProductEq, MinionDivEqUndefZero,...); …

 perf: reduce size of AST types 

---

Cargo.lock
conjure_oxide/tests/rewrite_tests.rs
crates/conjure_core/Cargo.toml
crates/conjure_core/src/ast/atom.rs
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/ast/literals.rs
crates/conjure_core/src/solver/adaptors/minion/parse_model.rs
crates/conjure_rules/src/minion.rs
perf_benchmarks/run_all.sh

Further reduce the size of `Expression` by boxing many of the larger
flat / Minion variants. This is a followup to 6012de809 (perf: reduce
size of AST types, 2025-06-18), for a more detailed explanation and
motivation for this change, see the message for that commit.
Making `Expression` under 128 bytes should make moving our types use
inline code code instead of `memcpy`, which is cheaper [1].
This further improves performance in some of the standard benchmarks:
Benchmark                                 | % speedup vs main
---------                                 | -----------------
models/fast/langford.eprime               | 14%
models/fast/nqueens_8.eprime              | 10%
models/fast/xkcd.eprime                   | 13%
models/slow/nqueens_20.eprime             | 3% …

perf: further reduce size of `Expression` from 152 to 96 bytes

---

crates/conjure_core/src/ast/domains.rs
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/ast/mod.rs
crates/conjure_core/src/ast/types.rs
crates/conjure_rules/src/constant_eval.rs
crates/conjure_rules/src/select_representation.rs

* When operating on or creating Integer domains, create domains with bounded ranges instead of just single elements: e.g. write the domain containing `{1,2,4,5,6}` as `int(1..2,4..6)` instead of `int(1,2,4,5,6)`.
This is done through the new `from_slice_i32` and `from_set_i32` methods, which are called from all the other domain operations when they need to create a domain. These replace the removed `make_int_domain_from_values_i32` method.
* Replace `Option<Domain>` with a more descriptive error result type, `Result<Domain,DomainOpError>`. `DomainOpError` encodes the reason that a domain operation failed; e.g. the input domain type was wrong, the input domain was unbounded. This commit also adds an error section to the documentation of each function, detailing the circumstances in which …

feat(ast): cleanup `Domain`, output bounded domains from domain methods

---

crates/conjure_core/src/ast/atom.rs
crates/conjure_core/src/ast/domains.rs
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/ast/literals.rs
crates/conjure_core/src/ast/types.rs

**Based on #906**
---
This PR is the start of work to make `domain_of()` return a `Domain`, not a `Option<Domain>` , as discussed in issue #876.  It introduces the `HasDomain` trait central to this effort. Then, it begins filling in some missing return types, which is needed before we start implementing `HasDomain` everywhere.
For more details, see the commit log.

Begin refactoring types to use `HasDomain` trait

---

crates/conjure_core/src/ast/declaration.rs
crates/conjure_core/src/ast/mod.rs

Add `DeclarationPtr` type, and implement the `ReturnType` and `Biplate` traits
on it, as discussed in issue #911.
Note that this PR is expected to fail hygene checks, as it deprecates the `Declaration` type, resulting in `deprecated type used` warnings. Follow up PRs will replace all usages `Rc<RefCell<Declaration>>` with `DeclarationPtr`, allowing me to remove all usages of `Declaration`. I am putting that refactor in a seperate PR, as it will be a large change.
Tracking-Issue: #910
For more information, see the commit log:
* * * * * 
- **feat(ast): add `DeclarationPtr`**
Add `DeclarationPtr` type, representing a shared pointer to a
`Declaration`.
In future commits, I intend to replace all usages of
`Rc<RefCell<Declaration>>`, which we currently use as the shared pointer
type, with …

[`DeclarationPtr` 01] Add `DeclarationPtr`

---

conjure_oxide/tests/essence_macro_tests/mod.rs
crates/conjure-cp-core/src/ast/atom.rs
crates/conjure-cp-essence-macros/src/lib.rs

Remove `Atom::new_ilit()` / `Atom::new_blit()` as they are not necessary now that we have a proper `From` implementation. Also remove some commented out macro tests.

refactor(ast): remove Atom::new_ilit()

---

Cargo.lock
crates/conjure-cp-cli/src/solve.rs
crates/conjure-cp-cli/src/utils/conjure.rs
crates/conjure-cp-essence-macros/src/expand.rs
crates/conjure-cp-essence-macros/src/expression.rs
crates/conjure-cp-essence-parser/Cargo.toml
crates/conjure-cp-essence-parser/src/errors.rs
crates/conjure-cp-essence-parser/src/parser/expression.rs
crates/conjure-cp-essence-parser/src/parser/parse_exprs.rs
crates/conjure-cp-essence-parser/src/parser/parse_model.rs
crates/conjure-cp/tests/essence_macro_tests.rs
tests-integration/tests/integration_tests.rs

Previously, the error messages produced by the parser (and, consequently, the essence macros) were not very helpful.
For example:
There was also an `.unwrap()` in one of the match arms that caused the macro to panic with no proper error message at all
This patch refactors the `EssenceParseError` enum:
-  Instead of wrapping `conjure-cp-core::Error` in one of its variants, it implements `From<conjure-cp-core::Error>`.
This avoids the "nested" error messages seen above
- The `SyntaxError` variant (previously `ParseError`) contains an optional range pinpointing the problematic expression
Error handling in the essence macro has also been improved slightly
With these changes, we can now produce semi-useful compiler errors like:

refactor(parser, macros): improve parser errors

---

crates/conjure-cp-essence-parser/src/parser/expression.rs

For some names, `essence_expr!(&my_metavar)` seemed to get parsed as `" my_metavar"` when expanding macros, leading to invalid code.
For some reason, this only affected the "expand macro" action in the IDE, but did not seem to stop the entire project from compiling. (Possibly something specific to `rust-analyzer` or an environment issue).
This just adds an extra `.trim()` to ensure the metavar name never has any leading/trailing whitespace

hotfix: trim whitespace in metavars
