.github/dependabot.yml

@ozgurakgun given we have dependabot, would it be a good idea to use it for submodules too?

Use dependabot to update submodules

---

src/main.rs

fully functional, the other extreme

---

.github/workflows/coverage.yml
.gitignore
.gitmodules
etc/scripts/gen_coverage.sh
etc/scripts/gen_coverage_all.sh

This PR adds code coverage reports for cargo test.

CI: Code Coverage

---

.github/dependabot.yml

I should have noticed this in your PR @gskorokhod - hopefully fixed now.

Fix dependabot.yml, the pip section

---

.github/workflows/code-coverage-deploy.yml
.github/workflows/code-coverage.yml

Issue seems to be that workflow run uses the sha of last commit on main, not sha of the pr we want coverage for.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
Fixing this

Fix code coverage

---

.github/workflows/code-coverage.yml

Final one I hope! Just forgot to rename a thing that I renamed.

Fix small typo

---

.github/workflows/code-coverage-deploy.yml
.github/workflows/code-coverage.yml

Finally fix CI for code coverage

---

.gitignore
Cargo.lock
Cargo.toml
clippy.toml
solvers/minion/Cargo.toml
solvers/minion/build.rs
solvers/minion/src/ast.rs
solvers/minion/src/error.rs
solvers/minion/src/run.rs
solvers/minion/src/scoped_ptr.rs

As per #78  - I am removing unwrap and expects from minion_rs, and replacing them with Result<> returning.

Minion: more robust error handling, and make clippy happy

---

Cargo.lock
conjure_oxide/Cargo.toml
conjure_oxide/build.rs
conjure_oxide/src/error.rs
conjure_oxide/src/main.rs
conjure_oxide/src/parse.rs
conjure_oxide/src/solvers/error.rs
conjure_oxide/src/solvers/minion.rs
conjure_oxide/src/solvers/mod.rs
conjure_oxide/src/solvers/solver_list.rs
conjure_oxide/src/solvers/solvers.rs
solvers/chuffed/src/lib.rs
src/lib.rs

Better Error Handling

---

.github/workflows/oxide.yml
conjure_oxide/tests/generated_tests.rs

using a matrix configuration for github actions, just edited one of the actions for now

using a matrix configuration for github actions

---

conjure_oxide/src/lib.rs
conjure_oxide/src/main.rs
conjure_oxide/src/rules/mod.rs
conjure_oxide/src/solvers/minion.rs
conjure_oxide/tests/rewrite_tests.rs
crates/conjure_rules/src/lib.rs

Here I write some basic rules and simulate a full expression reduction and handoff to Minion. The problem I am using is XYZ, although we can later expand this to the set problem discussed in our week 2 meeting.
Based off #141

Manual Rewrite Proof of Concept

---

.github/workflows/code-coverage-deploy.yml

Fixes a bug in #208.
@ozgurakgun

Fix: New Code Coverage CI not triggering deploy action

---

.github/workflows/code-coverage-deploy.yml
.github/workflows/docs-generate.yml
tools/coverage.sh

Complete code coverage CI

---

Cargo.lock
conjure_oxide/Cargo.toml
crates/conjure_core/Cargo.toml
crates/conjure_core/src/rule_engine/mod.rs
crates/conjure_macros/Cargo.toml
doc/index.md

ci: complete rename of conjure_rules_proc_macro to conjure_macros

---

doc/index.md

Added testing instructions to API docs

Added testing instructions in doc

---

conjure_oxide/tests/generated_tests.rs

Added docstring to integration_test_inner

---

conjure_oxide/tests/integration/basic/div/05/input.expected-minion.solutions.json
conjure_oxide/tests/integration/basic/div/05/input.expected-rewrite.serialised.json
crates/conjure_core/src/rules/base.rs
crates/conjure_core/src/rules/bubble.rs
crates/conjure_core/src/rules/checks.rs
crates/conjure_core/src/rules/minion.rs
crates/conjure_core/src/rules/mod.rs

Fix multiple applicable rules errors from #401.

Fix multiple applicable rules

---

crates/conjure_core/src/rules/minion.rs

fix(rules/minion): fix Reduction::new wrong argument order

---

.gitmodules

Point minion submodule to main and update it

---

crates/conjure_core/src/ast/expressions.rs

fix(ast): implement domain_of for all expressions

---

conjure_oxide/tests/integration/eprime-minion/partial-eval-02-or-and/input-expected-rule-trace.json
conjure_oxide/tests/integration/eprime-minion/partial-eval-02-or-and/input-generated-rule-trace.json
conjure_oxide/tests/integration/eprime-minion/partial-eval-or-and/input-expected-rule-trace.json
conjure_oxide/tests/integration/eprime-minion/partial-eval-or-and/input-generated-rule-trace.json
crates/conjure_core/src/ast/literals.rs
crates/conjure_core/src/rules/constant.rs

fix: implement constant evaluation for all expressions

---

.github/workflows/code-coverage.yml
.github/workflows/docs.yml
.github/workflows/test.yml
.github/workflows/warnings.yml

ci: invalidate cache

---

conjure_oxide/src/main.rs
conjure_oxide/src/utils/conjure.rs
conjure_oxide/tests/generated_tests.rs

Takes optional command line argument -n <number> and passes it in to `get_minion_solutions` standard behaviour is same as before. 
Fixes #341

added command line option for requesting a specific number of solutions.

---

tools/ci/generate-doc-coverage-summary-md.bash

thanks for ths work on this @niklasdewally, it looks great.
minor update suggestion, should be self explanatory.

reorder the numbers so they are in non-decreasing order

---

Cargo.lock
crates/tree_morph/Cargo.toml
crates/tree_morph/src/helpers.rs
crates/tree_morph/tests/rule_groups.rs

bump tree_morph dependencies

---

.gitmodules

Point the repo to Georgii's fork of Minion to apply his fix for Minion build
failures (https://github.com/minion/minion/pull/43)

fix(minion): apply Georgiis hotfix for Minion build failure

---

crates/tree_morph/src/commands.rs
crates/tree_morph/src/engine.rs
crates/tree_morph/tests/enum_rules.rs
crates/tree_morph/tests/lambda_calc.rs

Reverts conjure-cp/conjure-oxide#694 - seems to have broken the build somehow...

Revert "refactor(tree_morph): mut_meta to use Box<dyn FnOnce(&mut M)>"

---

conjure_oxide/tests/generated_tests.rs

When ACCEPT=true, do not panic when the expected JSON is invalid.
Refactoring the AST data types can cause previously valid expected JSON
to become invalid. Before this commit, this would cause the tester to
panic. Now, instead of panicking, this causes the test to be marked as
failed, causing the expected JSON to be regenerated.

fix(tester): when ACCEPT=true, do not panic on JSON parsing errors

---

crates/tree_morph/benches/factorial.rs
crates/tree_morph/benches/left_add.rs
crates/tree_morph/benches/left_add_hard.rs
crates/tree_morph/benches/right_add.rs
crates/tree_morph/src/commands.rs
crates/tree_morph/src/engine.rs
crates/tree_morph/src/lib.rs
crates/tree_morph/tests/enum_rules.rs
crates/tree_morph/tests/lambda_calc.rs

@ozgurakgun Reopened refactor mut meta as you asked

refactor(tree_morph): mut_meta to use Box<dyn FnOnce(&mut M)> (reopened)

---

Cargo.lock
conjure_oxide/Cargo.toml
conjure_oxide/tests/generated_tests.rs
crates/conjure_core/Cargo.toml
crates/conjure_core/src/ast/expressions.rs
crates/conjure_core/src/ast/model.rs
crates/conjure_core/src/rule_engine/rule.rs
crates/tree_morph/src/commands.rs
crates/tree_morph/src/engine.rs
crates/tree_morph/src/lib.rs
crates/tree_morph/src/rule.rs

The aim of this pull request is to add an option to run conjure-oxide tests on treemorph.

Integrating tree-morph into conjure-oxide

---

conjure_oxide/src/main.rs
conjure_oxide/src/utils/essence_parser.rs
conjure_oxide/tests/generated_tests.rs
conjure_oxide/tests/parser_tests/mod.rs

feat: add option to use native parser when running main

---

conjure_oxide/src/cli.rs
conjure_oxide/src/solve.rs
conjure_oxide/src/test_solve.rs
crates/conjure_core/src/solver/adaptors/rustsat/convs.rs

draft pull request in order to set the solver to minion if no solver is passed in using the `--solver` argument

Hotfix: Default to minion if no solver is passed in the cli args

---

.github/dependabot.yml
.github/workflows/checks.yml
.github/workflows/code-coverage-deploy.yml
.github/workflows/code-coverage-main.yml
.github/workflows/code-coverage.yml
.github/workflows/docs.yml
.github/workflows/hygiene.yml
.github/workflows/test.yml

actions seem to fail with an sccache related error message. let's see if updating the version helps. also enabling dependabot for github actions.

fix(ci): update sccache version and enable dependabot for github actions

---

.github/workflows/code-coverage-deploy.yml

fix(ci): remove redundant actions/cache

---

conjure_oxide/src/cli.rs
conjure_oxide/src/solve.rs

Add --use-optimised-rewriter flag to use the tree-morph / dirty-clean rewriter instead of the naive one.
Closes: #949
Tracking-issue: #950

feat(cli): add --use-optimised-rewriter
